require "yaml"

def generateArgument(a, si)
    out = ""
    out << "<dt>Stack index #{si}: #{a["type"]}</dt>"
    out << "<dd>#{a["desc"]}</dd>"
    return out
end

def generateFunction(f)
    name = f.keys.first
    out = ""
    out << "<h3>#{name}</h3>"
    out << "<h4>Description</h4>"
    out << "<div class=\"info\">#{f[name]["desc"]}</div>"
    if !f[name]["note"].nil?
        f[name]["note"].each do |n|
            out << "<div class=\"info\">NOTE: #{n}</div>"
        end
    end
    if !f[name]["pops"].nil?
        out << "<div><h4>Pops</h4><dl class=\"info\">"
        f[name]["pops"].each_with_index do |a, i|
            out << generateArgument(a, f[name]["pops"].length - (i + 1))
        end
        out << "</dl></div>"
    end
    if !f[name]["pushes"].nil?
        out << "<div><h4>Pushes</h4><dl class=\"info\">"
        f[name]["pushes"].each_with_index do |a, i|
            out << generateArgument(a, f[name]["pushes"].length - (i + 1))
        end
        out << "</dl></div>"
    end
    out << %Q~
<div class="codeContainer">
    <button class="codeButton">
        Source (click to open/close)
    </button>
    <pre class="code">#{f[name]["source"]}</pre>
</div>~
    return out
end

def generateCategory(c)
    out = "<h3>#{c["category"]}</h3>"
    c["functions"].each do |f|
        out << generateFunction(f) << "\n"
    end
    return out
end


glossary = YAML.load_file("Glossary.yaml")

puts %Q~
<html>
    <head>
        <title>
            Charm Function Glossary
        </title>
        <script type="text/javascript">
            function codeClick(e) {
                var elem = e.target;
                var codePre = elem.parentElement.getElementsByClassName("code")[0];
                if (codePre.classList.contains("code-open")) {
                    codePre.classList.remove("code-open");
                    //codePre.style.height = "0";
                } else {
                    codePre.classList.add("code-open");
                    //var lineHeight = parseInt(window.getComputedStyle(codePre).lineHeight);
                    //codePre.style.height = (codePre.innerHTML.split("\\n").length * lineHeight) + "px";
                }
            }
            function init() {
                var codes = document.getElementsByClassName("codeButton");
                for (let code of codes) {
                    code.onclick = function (e) { codeClick(e); };
                }
            }
            window.onload = init;
        </script>
        <style type="text/css">
            html {
                background-color: #ddd;
            }
            body {
                width: 80%;
                min-width: 30em;
                margin: 0 auto;
                padding: 4em;
                padding-top: 2em;
                box-shadow: 0 0 100px black;
                background-color: #fff;
            }
            .info {
                padding-left: 2em;
                margin-top: 0.5em;
                margin-bottom: 0.5em;
            }
            .code {
                overflow-y: hidden;
                background-color: #ccc;
                height: 0;
                padding: 0;
                margin: 0;

                transition: padding 0.5s cubic-bezier(0, 1, 0, 1);
                transition: margin 0.5s cubic-bezier(0, 1, 0, 1);
            }

            .code-open {
                padding: 1em;
                margin-top: 0.75em;
                margin-bottom: 0.75em;
                height: auto;
            }
        </style>
    </head>
    <body>
        <h1>
            Charm Function Glossary
        </h1>
        <p>
            This page was autogenerated by docs/GenerateGlossary.rb on #{Time.now}. It lists all of the functions in the Charm glossary in an easy to read, useful reference format.
        </p>
        <h2>
            Native Functions
        </h2>
        #{glossary["native_functions"].map { |c| generateCategory c }.join("\n")}
        <h2>
            Prelude Functions
        </h2>
</html>~
